# Generated by Django 4.1.3 on 2023-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
