# Generated by Django 4.1.3 on 2023-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0002_alter_caption_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caption',
            old_name='isbn',
            new_name='imageID',
        ),
    ]
